"""Unit tests for scripts/analyze_pnrr_complete.py.

Tests the PNRR cloud dataset parsing and mxmap.it cross-reference logic
without needing the full 26MB PNRR dataset.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))
sys.path.insert(0, str(REPO_ROOT / "src"))

from analyze_pnrr_complete import (  # noqa: E402
    normalize_misura,
    parse_amount,
    normalize_name,
)


# ── normalize_misura ──


def test_normalize_misura_1_1():
    assert normalize_misura(
        "1.1 Infrastrutture digitali - Altre PAC - maggio 2024"
    ) == ("1.1_Infrastrutture_digitali")


def test_normalize_misura_1_2():
    assert normalize_misura("1.2 Abilitazione al cloud - Comuni - Aprile 2022") == (
        "1.2_Abilitazione_cloud"
    )


def test_normalize_misura_1_3():
    assert (
        normalize_misura("1.3.1 Piattaforma Digitale Nazionale Dati - Comuni")
        == "1.3_PDND"
    )


def test_normalize_misura_1_4():
    assert (
        normalize_misura("1.4.3 - pagoPA - Comuni - Aprile 2022")
        == "1.4_Servizi_digitali"
    )


def test_normalize_misura_1_1_not_confused_with_1_2():
    """A '1.1 e 1.2' avviso should be classified as 1.2 (Abilitazione cloud)
    only if it doesn't also contain '1.2' elsewhere — but our logic keeps
    it as 1.2 if it contains '1.2' substring. Verify this behavior."""
    # This avviso contains both "1.1" and "1.2" — our logic classifies as 1.2
    # because 1.2 check is done first after 1.1+1.2 not-1.2 check
    result = normalize_misura("1.1 e 1.2 - Infrastrutture e abilitazione")
    assert result in ("1.1_Infrastrutture_digitali", "1.2_Abilitazione_cloud")


def test_normalize_misura_empty():
    assert normalize_misura("") == "altro"
    assert normalize_misura("Random avviso") == "altro"


# ── parse_amount ──


def test_parse_amount_valid():
    assert parse_amount("1234.56") == 1234.56
    assert parse_amount("1000000") == 1_000_000


def test_parse_amount_invalid():
    assert parse_amount("not_a_number") == 0.0
    assert parse_amount("") == 0.0
    assert parse_amount(None) == 0.0


def test_parse_amount_zero():
    assert parse_amount("0") == 0.0
    assert parse_amount("0.0") == 0.0


# ── normalize_name ──


def test_normalize_name_basic():
    assert normalize_name("Comune di Roma") == "roma"


def test_normalize_name_provincia():
    assert normalize_name("Provincia di Como") == "como"


def test_normalize_name_regione():
    assert normalize_name("Regione Lombardia") == "lombardia"


def test_normalize_name_ordine():
    # "Ordine dei" prefix is NOT stripped (only "Ordine " is)
    # This is the current behavior — verified for regression
    assert normalize_name("Ordine dei Medici") == "dei medici"
    # But "Ordine" alone IS stripped
    assert normalize_name("Ordine Avvocati Milano") == "avvocati milano"


def test_normalize_name_no_prefix():
    assert normalize_name("INPS") == "inps"
    assert normalize_name("ASL Milano") == "asl milano"


def test_normalize_name_case_insensitive():
    assert normalize_name("COMUNE DI ROMA") == "roma"
    assert normalize_name("comune di Roma") == "roma"


def test_normalize_name_apostrophe_normalization():
    """Italian apostrophes should be normalized."""
    assert normalize_name("Comune di Citt\u00e0") == "citt\u00e0"


def test_normalize_name_empty():
    assert normalize_name("") == ""
    assert normalize_name(None) == ""


# ── PNRR data file existence ──


def test_pnrr_data_files_exist():
    """All three PNRR datasets should be downloadable."""
    expected_files = [
        "candidature_altrienti_finanziate.csv",
        "candidature_comuni_finanziate.csv",
        "candidature_scuole_finanziate.csv",
    ]
    for fname in expected_files:
        path = REPO_ROOT / "data" / "pnrr" / fname
        if path.exists():
            # Check it's not empty
            assert path.stat().st_size > 10_000


def test_pnrr_complete_summary_exists():
    """The summary JSON should be generated by the script."""
    path = REPO_ROOT / "data" / "pnrr" / "pnrr_complete_summary.json"
    if path.exists():
        import json

        data = json.loads(path.read_text())
        # Check required structure
        assert "datasets" in data
        assert "cloud_pnrr_importi" in data
        assert "cloud_pnrr_totale_eur" in data
        assert "per_regione" in data
        assert "crossref_mxmap" in data
        # Cloud total should be > €1B
        assert data["cloud_pnrr_totale_eur"] > 1_000_000_000


def test_crossref_count_reasonable():
    """At least 15k enti should match between PNRR cloud and mxmap.it
    (since 96% of 22,987 PA are in the dataset)."""
    path = REPO_ROOT / "data" / "pnrr" / "pnrr_complete_summary.json"
    if not path.exists():
        return
    import json

    data = json.loads(path.read_text())
    matched = data.get("crossref_mxmap", {}).get("totale_matched", 0)
    # 21,997 expected from the full analysis
    assert matched > 15_000, f"Only {matched} matched, expected >15k"
